import {
    BookOpenText,
    Briefcase,
    CheckSquareOffset,
    CalendarBlank,
    CalendarDots,
    CalendarX,
    ChartLineUp,
    ChartBar,
    ClockCounterClockwise,
    Desktop,
    FlowArrow,
    Gauge,
    Pulse,
    GearSix,
    HourglassMedium,
    House,
    type Icon,
    ListChecks,
    NotePencil,
    Sliders,
    UserSwitch,
    UsersFour,
    Users,
    UsersThree,
} from '@phosphor-icons/react';

/** Phosphor Bold icons per navigation key, as in the mockup kit. */
export const navIcons: Record<string, Icon> = {
    my_day: House,
    history: CalendarBlank,
    overtime: HourglassMedium,
    my_tasks: CheckSquareOffset,
    activity_log: NotePencil,
    team_today: Users,
    approvals: ListChecks,
    projects: Briefcase,
    reports: ChartBar,
    calendar: CalendarDots,
    people: UsersThree,
    teams: UsersFour,
    imposter: UserSwitch,
    corrections: NotePencil,
    devices: Desktop,
    rules: Sliders,
    app_settings: GearSix,
    guide: BookOpenText,
    audit: ClockCounterClockwise,
    leave: CalendarX,
    leave_approvals: CalendarX,
    leave_admin: CalendarX,
    work_monitor: ChartLineUp,
    workload: Gauge,
    pipeline: FlowArrow,
    activity_monitor: Pulse,
    monitoring: Gauge,
    settings: GearSix,
};
