import {
    Briefcase,
    CalendarBlank,
    CalendarDots,
    ChartBar,
    ClockCounterClockwise,
    Desktop,
    HourglassMedium,
    House,
    type Icon,
    ListChecks,
    NotePencil,
    Sliders,
    UserSwitch,
    UsersFour,
    Users,
    UsersThree,
} from '@phosphor-icons/react';

/** Phosphor Bold icons per navigation key, as in the mockup kit. */
export const navIcons: Record<string, Icon> = {
    my_day: House,
    history: CalendarBlank,
    overtime: HourglassMedium,
    my_tasks: Briefcase,
    activity_log: NotePencil,
    team_today: Users,
    approvals: ListChecks,
    projects: Briefcase,
    reports: ChartBar,
    calendar: CalendarDots,
    people: UsersThree,
    teams: UsersFour,
    imposter: UserSwitch,
    corrections: NotePencil,
    devices: Desktop,
    rules: Sliders,
    audit: ClockCounterClockwise,
};
